### ISSUE TITLE
[BUG] Doesn't seem to play nice with spaces in usernames \ TEMP\audio.wav not found

### ISSUE THREAD

**Issue by SamTheGreatCoder** [ThatOneCalculator/PyJumpcutterV2#10]
```
PS C:\Users\username with space\Downloads\pyjumpcutter> & "C:/Program Files (x86)/Python38-32/python.exe" "c:/Users/username with space/Downloads/pyjumpcutter/jumpcutter.py"       
Jumpcutter made by carykh and ThatOneCalculator! Enter Y for youtube video, Q for quit, or anything else to choose a file


Enter C for custom values, else hit enterc
Enter frame rate. Leave blank for default.
25
Enter sample rate. Leave blank for default.

Enter silent threshold. The volume amount that frames' audio needs to surpass to be consider "sounded". It ranges from 0 (silence) to 1 (max volume). Leave blank for default.

Enter silent threshold. Leave blank for default.

Enter silent speed. Leave blank for default.

Enter sounded speed. The speed that sounded (spoken) frames should be played at. Typically 1. Leave blank for default.

Enter frame quality. Leave blank for default.

C:/Users/username: No such file or directory
ffmpeg version git-2019-11-18-d831edc Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.2.1 (GCC) 20191010
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy 
--enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 36.100 / 56. 36.100
  libavcodec     58. 62.100 / 58. 62.100
  libavformat    58. 35.100 / 58. 35.100
  libavdevice    58.  9.101 / 58.  9.101
  libavfilter     7. 66.100 /  7. 66.100
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
C:/Users/username: No such file or directory
Traceback (most recent call last):
  File "c:/Users/username with space/Downloads/pyjumpcutter/jumpcutter.py", line 131, in <module>
    sampleRate, audioData = wavfile.read(TEMP_FOLDER+"/audio.wav")
  File "C:\Users\username with space\AppData\Roaming\Python\Python38\site-packages\scipy\io\wavfile.py", line 233, in read
    fid = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'TEMP/audio.wav'
PS C:\Users\username with space\Downloads\pyjumpcutter>
```
My actual Windows username is something else, but for the purpose of identity protection, I've changed it something else, that still properly represents the issue.
Windows 10 1903, Python 3.8, running in PowerShell, through Visual Studio Code.

If it's a Windows problem, I am familiar with macOS and Linux as well.

**Comment by SamTheGreatCoder** [comment]
Update: Moved the entire workspace folder to an SD card, and it seems to be running fine, although I wouldn't consider 144p25 fine at only realtime speeds, this is all on a Samsung UHS-1 SD Card. Will update later. Currently converting video.

**Comment by SamTheGreatCoder** [comment]
``
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS E:\pyjumpcutter> & "C:/Program Files (x86)/Python38-32/python.exe" e:/pyjumpcutter/jumpcutter.py
Jumpcutter made by carykh and ThatOneCalculator! Enter Y for youtube video, Q for quit, or anything else to choose a file


Enter C for custom values, else hit enterc
Enter frame rate. Leave blank for default.
25
Enter sample rate. Leave blank for default.

Enter silent threshold. The volume amount that frames' audio needs to surpass to be consider "sounded". It ranges from 0 (silence) to 1 (max volume). Leave blank for default.

Enter silent threshold. Leave blank for default.

Enter silent speed. Leave blank for default.

Enter sounded speed. The speed that sounded (spoken) frames should be played at. Typically 1. Leave blank for default.

Enter frame quality. Leave blank for default.

Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'E:/pyjumpcutter/video.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    title           : 25 Apple Macbook From eBay Gets Restored
    encoder         : Lavf58.29.100
  Duration: 00:10:58.59, start: 0.000000, bitrate: 178 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 256x144 [SAR 1:1 DAR 16:9], 44 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)      
    Metadata:
      handler_name    : ISO Media file produced by Google Inc.
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      handler_name    : ISO Media file produced by Google Inc.
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> mjpeg (native))
Press [q] to stop, [?] for help
[swscaler @ 0000023ac0d3ae80] deprecated pixel format used, make sure you did set range correctly
Output #0, image2, to 'TEMP/frame%06d.jpg':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    title           : 25 Apple Macbook From eBay Gets Restored
    encoder         : Lavf58.35.100
    Stream #0:0(und): Video: mjpeg, yuvj420p(pc), 256x144 [SAR 1:1 DAR 16:9], q=2-31, 200 kb/s, 25 fps, 25 tbn, 25 tbc (default)
    Metadata:
      handler_name    : ISO Media file produced by Google Inc.
      encoder         : Lavc58.62.100 mjpeg
    Side data:
      cpb: bitrate max/min/avg: 0/0/200000 buffer size: 0 vbv_delay: N/A
frame=16463 fps= 26 q=2.0 Lsize=N/A time=00:10:58.52 bitrate=N/A speed=1.05x
video:156527kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
ffmpeg version git-2019-11-18-d831edc Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.2.1 (GCC) 20191010
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy 
--enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 36.100 / 56. 36.100
  libavcodec     58. 62.100 / 58. 62.100
  libavformat    58. 35.100 / 58. 35.100
  libavdevice    58.  9.101 / 58.  9.101
  libavfilter     7. 66.100 /  7. 66.100
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'E:/pyjumpcutter/video.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    title           : 25 Apple Macbook From eBay Gets Restored
    encoder         : Lavf58.29.100
  Duration: 00:10:58.59, start: 0.000000, bitrate: 178 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 256x144 [SAR 1:1 DAR 16:9], 44 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)      
    Metadata:
      handler_name    : ISO Media file produced by Google Inc.
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      handler_name    : ISO Media file produced by Google Inc.
Expected number for ar but found: -vn
Traceback (most recent call last):
  File "e:/pyjumpcutter/jumpcutter.py", line 131, in <module>
    sampleRate, audioData = wavfile.read(TEMP_FOLDER+"/audio.wav")
  File "C:\Users\username with space\AppData\Roaming\Python\Python38\site-packages\scipy\io\wavfile.py", line 233, in read
    fid = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'TEMP/audio.wav'
PS E:\pyjumpcutter>
``
EDIT: put the terminal output in a code block and add say what the heck is going on.

So, the video converted, or at least I think it did, as all the image files are in the populating temp folder, but it's complaining about the audio.wav file being missing, when it truly is missing.

**Comment by SamTheGreatCoder** [comment]
I am creating my own fork, then fixing some of the issues I'm having, for now, I'm going to close it.
