### ISSUE TITLE
Errors when trying to download from YouTube url

### ISSUE THREAD

**Issue by FilipeMarch** [ThatOneCalculator/PyJumpcutterV2#3]
Opened the jumpcutter folder on terminal, typed 'python jumpcutter.py'
Type Y, paste this youtube link on the dialog box https://www.youtube.com/watch?v=NCFg7G63KgI

This error comes: 
Downloading  youtube.com/watch?v=NCFg7G63KgI
Enter C for custom values, else hit enter
Traceback (most recent call last):
  File "jumpcutter.py", line 108, in <module>
    INPUT_FILE = downloadFile(urlget)
  File "jumpcutter.py", line 13, in downloadFile
    name = YouTube(url).streams.first().download()
  File "/home/filipemarch/anaconda3/lib/python3.7/site-packages/pytube/__main__.py", line 88, in __init__
    self.prefetch_init()
  File "/home/filipemarch/anaconda3/lib/python3.7/site-packages/pytube/__main__.py", line 97, in prefetch_init
    self.init()
  File "/home/filipemarch/anaconda3/lib/python3.7/site-packages/pytube/__main__.py", line 133, in init
    mixins.apply_signature(self.player_config_args, fmt, self.js)
  File "/home/filipemarch/anaconda3/lib/python3.7/site-packages/pytube/mixins.py", line 49, in apply_signature
    signature = cipher.get_signature(js, stream['s'])
KeyError: 's'

I've done the same steps other times, and got this error:

Expected number for ar but found: -vn
Traceback (most recent call last):
  File "jumpcutter.py", line 131, in <module>
    sampleRate, audioData = wavfile.read(TEMP_FOLDER+"/audio.wav")
  File "/home/filipemarch/anaconda3/lib/python3.7/site-packages/scipy/io/wavfile.py", line 233, in read
    fid = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'TEMP/audio.wav'

Sometimes the algorithm just works. Sometimes it throws these errors. 

EDIT

I found that if I don't change the default values, the algorithm works. Whenever I try to modify any default values, it stops working, throwing the error FileNotFoundError: [Errno 2] No such file or directory: 'TEMP/audio.wav'

Actually, when I run python jumpcutter.py and it asks me "Enter C for custom values, else hit enter", if you enter C, the algorithm will always fail, even if I just press enter on all asked values afterwards.

**Comment by soopyc** [comment]
have you fixed your problems yet? :)

**Comment by Extemma** [comment]
I'm sure you already thought of this, but the best quick'n'dirty work around I could find is to manually change the default values in the script itself.

**Comment by hbmartin** [comment]
@FilipeMarch @kcomain @Extemma @ThatOneCalculator this error is fixed in new, actively maintained, Python3 only pytube fork: https://github.com/hbmartin/pytube3
