### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by pullup** [ThatOneCalculator/PyJumpcutterV2#7]
Getting this bug quite often. Any idea the cause?
```  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.3.100
  Duration: 00:08:13.80, start: 0.000000, bitrate: 1737 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 1606 kb/s, 15 fps, 15 tbr, 15360 tbn, 30 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 127 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
Expected number for ar but found: -vn
Traceback (most recent call last):
  File ".\jumpcutter.py", line 131, in <module>
    sampleRate, audioData = wavfile.read(TEMP_FOLDER+"/audio.wav")
  File "C:\Users\yewsir\AppData\Local\Programs\Python\Python37-32\lib\site-packages\scipy\io\wavfile.py", line 233, in read
    fid = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'TEMP/audio.wav'```

**Comment by ThatOneCalculator** [comment]
Remove the TEMP folder and try again
